lint: add explicit codegen type annotation
```
>deno publish --dry-run
Checking for slow types in the public API...
error[missing-explicit-type]: missing explicit type in the public API
  --> C:\Users\ethan\Documents\GitHub\ht\cli\codegen.ts:26:14
   |
26 | export const bcdElementEventNames = Object.keys(bcd.api.Element)
   |              ^^^^^^^^^^^^^^^^^^^^ this symbol is missing an explicit type
   |
   = hint: add an explicit type annotation to the symbol

  info: all symbols in the public API must have an explicit type
  docs: https://jsr.io/go/slow-type-missing-explicit-type

This package contains errors for slow types. Fixing these errors will:

  1. Significantly improve your package users' type checking performance.
  2. Improve the automatic documentation generation.
  3. Enable automatic .d.ts generation for Node.js.

Don't want to bother? You can choose to skip this step by
providing the --allow-slow-types flag.

error: Found 1 problem
```